version: '3.7'
services:
  category-postgresql:
    image: postgres:12.5
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - custom_network
networks:
  custom_network:
